"""
Metabolite mappings for BacDive unmapped metabolites.
Researched CHEBI and PubChem IDs for metabolites.
Generated on 2025-11-18
"""

METABOLITE_MAPPINGS = {
    # Top priority metabolites (>1000 occurrences)
    "Potassium 5-ketogluconate": {"chebi": None, "pubchem": "23702137", "occurrences": 7610},
    "Potassium 2-ketogluconate": {"chebi": None, "pubchem": None, "occurrences": 6705},
    "casein": {"chebi": None, "pubchem": None, "occurrences": 1586},  # Protein - not in CHEBI/PubChem small molecule databases

    # High priority (>100 occurrences)
    "esculin ferric citrate": {"chebi": "CHEBI:4853", "pubchem": "5281417", "occurrences": 444},  # Using esculin IDs
    "potassium 5-dehydro-D-gluconate": {"chebi": None, "pubchem": "23702137", "occurrences": 430},  # Same as Potassium 5-ketogluconate
    "potassium 2-dehydro-D-gluconate": {"chebi": None, "pubchem": None, "occurrences": 392},
    "yeast extract": {"chebi": None, "pubchem": None, "occurrences": 188},  # Complex mixture
    "peptone": {"chebi": None, "pubchem": None, "occurrences": 163},  # Complex protein hydrolysate
    "milk": {"chebi": None, "pubchem": None, "occurrences": 137},  # Complex mixture
    "casamino acids": {"chebi": None, "pubchem": None, "occurrences": 118},  # Complex amino acid mixture
    "L-alanine 4-nitroanilide": {"chebi": None, "pubchem": None, "occurrences": 113},

    # Medium priority (10-100 occurrences)
    "skimmed milk": {"chebi": None, "pubchem": None, "occurrences": 89},  # Complex mixture
    "2-oxogluconate": {"chebi": "CHEBI:16810", "pubchem": "164533", "occurrences": 73},  # Alpha-ketoglutarate anion
    "tryptone": {"chebi": None, "pubchem": None, "occurrences": 71},  # Complex protein hydrolysate
    "L-lactate": {"chebi": "CHEBI:422", "pubchem": "107689", "occurrences": 66},
    "maltose hydrate": {"chebi": None, "pubchem": None, "occurrences": 66},
    "1 % sodium lactate": {"chebi": None, "pubchem": None, "occurrences": 59},
    "O-nitrophenyl-beta-D-galactopyranosid": {"chebi": None, "pubchem": None, "occurrences": 58},
    "polysaccharides": {"chebi": None, "pubchem": None, "occurrences": 50},  # Generic class
    "corn oil": {"chebi": None, "pubchem": None, "occurrences": 44},  # Complex mixture
    "L-proline-4-nitroanilide": {"chebi": None, "pubchem": None, "occurrences": 39},
    "4-nitrophenyl beta-D-galactopyranoside hydrolysate": {"chebi": None, "pubchem": None, "occurrences": 37},
    "casein hydrolysate": {"chebi": None, "pubchem": None, "occurrences": 34},  # Complex protein hydrolysate
    "n-acetyl-neuraminic acid": {"chebi": None, "pubchem": None, "occurrences": 34},
    "alpha-hydroxybutyrate": {"chebi": None, "pubchem": None, "occurrences": 34},
    "yeast extract (0.01 %, w/v)": {"chebi": None, "pubchem": None, "occurrences": 26},  # Complex mixture
    "D-lactate": {"chebi": None, "pubchem": None, "occurrences": 26},
    "D-lactic acid methyl ester": {"chebi": None, "pubchem": None, "occurrences": 26},
    "3-O-methyl alpha-D-glucopyranoside": {"chebi": None, "pubchem": None, "occurrences": 25},
    "gamma-L-glutamate-4-nitroanilide": {"chebi": None, "pubchem": None, "occurrences": 22},
    "egg yolk": {"chebi": None, "pubchem": None, "occurrences": 20},  # Complex mixture
    "trimethoxybenzoate": {"chebi": None, "pubchem": None, "occurrences": 17},
    "crab shell chitin": {"chebi": None, "pubchem": None, "occurrences": 17},
    "methyl alpha-D-xylopyranoside": {"chebi": None, "pubchem": None, "occurrences": 17},
    "2,3-butanediol": {"chebi": None, "pubchem": "262", "occurrences": 16},
    "L-glutamate-gamma-3-carboxy-4-nitroanilide": {"chebi": None, "pubchem": None, "occurrences": 14},
    "crystalline cellulose": {"chebi": None, "pubchem": None, "occurrences": 13},
    "(-)-D-rhamnose": {"chebi": None, "pubchem": None, "occurrences": 11},
    "fermented rumen extract": {"chebi": None, "pubchem": None, "occurrences": 11},  # Complex mixture
    "esculin hydrolysate": {"chebi": None, "pubchem": None, "occurrences": 11},
    "2-deoxythymidine-5'-4-nitrophenyl phosphate": {"chebi": None, "pubchem": None, "occurrences": 11},
    "beef extract": {"chebi": None, "pubchem": None, "occurrences": 10},  # Complex mixture
    "(+)-D-glycogen": {"chebi": None, "pubchem": None, "occurrences": 10},
    "ferrihydrite": {"chebi": None, "pubchem": None, "occurrences": 10},

    # Lower priority (<10 occurrences)
    "synanthrin": {"chebi": None, "pubchem": None, "occurrences": 9},
    "butanol": {"chebi": "CHEBI:28885", "pubchem": "263", "occurrences": 8},  # n-butanol
    "sodium malate": {"chebi": None, "pubchem": None, "occurrences": 8},
    "manganese dioxide": {"chebi": "CHEBI:136511", "pubchem": "14801", "occurrences": 7},
    "soyton": {"chebi": None, "pubchem": None, "occurrences": 7},
    "hydroxy-L-proline": {"chebi": None, "pubchem": None, "occurrences": 7},
    "(2)-D-lactose": {"chebi": None, "pubchem": None, "occurrences": 6},
    "amorphous iron (iii) oxide": {"chebi": None, "pubchem": None, "occurrences": 6},
    "sodium(+)": {"chebi": None, "pubchem": None, "occurrences": 6},
    "(+)-D-galactose": {"chebi": None, "pubchem": None, "occurrences": 5},
    "meat extract": {"chebi": None, "pubchem": None, "occurrences": 5},  # Complex mixture
    "DL-2-gamma-aminobutyrate": {"chebi": None, "pubchem": None, "occurrences": 5},
    "olive oil": {"chebi": None, "pubchem": None, "occurrences": 5},  # Complex mixture
    "casitone": {"chebi": None, "pubchem": None, "occurrences": 5},  # Complex protein hydrolysate
    "indoxyl acetate": {"chebi": None, "pubchem": None, "occurrences": 5},
    "goethite": {"chebi": None, "pubchem": None, "occurrences": 4},
    "glycyl-L-bromosuccinic glutamic acid": {"chebi": None, "pubchem": None, "occurrences": 4},
    "trehalose dihydrate": {"chebi": None, "pubchem": None, "occurrences": 4},
    "Bacteriochlorophyll alpha": {"chebi": None, "pubchem": None, "occurrences": 4},
    "(+)-L-aspartate": {"chebi": None, "pubchem": None, "occurrences": 3},
    "casamino acids (0.01 %, w/v)": {"chebi": None, "pubchem": None, "occurrences": 3},  # Complex amino acid mixture
    "peptone (0.01 %, w/v)": {"chebi": None, "pubchem": None, "occurrences": 3},  # Complex protein hydrolysate
    "(+)-D-mannose": {"chebi": None, "pubchem": None, "occurrences": 3},
    "(+)-D-xylose": {"chebi": None, "pubchem": None, "occurrences": 3},
    "(+)-L-rhamnose": {"chebi": None, "pubchem": None, "occurrences": 3},
    "1-o-methyl alpha-galactopyranoside": {"chebi": None, "pubchem": None, "occurrences": 3},
    "rumen extract": {"chebi": None, "pubchem": None, "occurrences": 3},  # Complex mixture
    "D-galactose": {"chebi": None, "pubchem": None, "occurrences": 3},
    "1,2-butandiol": {"chebi": None, "pubchem": None, "occurrences": 3},
    "sedoheptulosan": {"chebi": None, "pubchem": None, "occurrences": 3},
    "amorphous fe(iii) oxyhydroxid": {"chebi": None, "pubchem": None, "occurrences": 3},
    "proteose": {"chebi": None, "pubchem": None, "occurrences": 3},  # Complex protein hydrolysate
    "polypeptone": {"chebi": None, "pubchem": None, "occurrences": 3},  # Complex protein hydrolysate
    "maltose": {"chebi": "CHEBI:17306", "pubchem": "439186", "occurrences": 3},
    "L-pyroglutamic acid": {"chebi": None, "pubchem": None, "occurrences": 3},
    "(+)-L-glutamate": {"chebi": None, "pubchem": None, "occurrences": 2},
    "(+)-L-ornithine": {"chebi": None, "pubchem": None, "occurrences": 2},
    "(2)-D-fructose": {"chebi": None, "pubchem": None, "occurrences": 2},
    "(+)-D-glucosamine": {"chebi": None, "pubchem": None, "occurrences": 2},
    "(2)-D-lyxose": {"chebi": None, "pubchem": None, "occurrences": 2},
    "(+)-L-lyxitol": {"chebi": None, "pubchem": None, "occurrences": 2},
    "L-aniline-4-nitroanilide": {"chebi": None, "pubchem": None, "occurrences": 2},
    "6-O-alpha-D-glucopyranosyl-D-gluconic acid": {"chebi": None, "pubchem": None, "occurrences": 2},
    "esculin": {"chebi": "CHEBI:4853", "pubchem": "5281417", "occurrences": 2},
    "L-alanine": {"chebi": "CHEBI:16977", "pubchem": "5950", "occurrences": 2},
    "aburamycin A": {"chebi": None, "pubchem": None, "occurrences": 2},
    "setamycin": {"chebi": None, "pubchem": None, "occurrences": 2},
    "neomycin E": {"chebi": None, "pubchem": None, "occurrences": 2},
    "neomycin F": {"chebi": None, "pubchem": None, "occurrences": 2},
    "bottromycin": {"chebi": None, "pubchem": None, "occurrences": 2},
    "actinomycin X": {"chebi": None, "pubchem": None, "occurrences": 2},
    "carbomycin": {"chebi": None, "pubchem": None, "occurrences": 2},
    "eurocidin": {"chebi": None, "pubchem": None, "occurrences": 2},
    "2-oxoglutarate": {"chebi": "CHEBI:16810", "pubchem": "164533", "occurrences": 2},  # Same as 2-oxogluconate
    "4-nitrophenyl phosphate disodium salt": {"chebi": None, "pubchem": None, "occurrences": 2},
    "sodium fumarate": {"chebi": None, "pubchem": None, "occurrences": 2},
    "methyl alpha-D-glucopyranoside": {"chebi": None, "pubchem": None, "occurrences": 2},
    "synthetic sea salts (sss)": {"chebi": None, "pubchem": None, "occurrences": 2},  # Complex mixture
    "L-glycine": {"chebi": "CHEBI:15428", "pubchem": "750", "occurrences": 2},
    "4-nitrophenyl-alpha-D-maltopyranoside": {"chebi": None, "pubchem": None, "occurrences": 2},
    "dipic acid": {"chebi": None, "pubchem": None, "occurrences": 2},
    "Ny-carrageenan": {"chebi": None, "pubchem": None, "occurrences": 2},
    "My-carrageenan": {"chebi": None, "pubchem": None, "occurrences": 2},
    "locust bean gum": {"chebi": None, "pubchem": None, "occurrences": 2},  # Complex polysaccharide
    "crude oil": {"chebi": None, "pubchem": None, "occurrences": 2},  # Complex mixture

    # Single occurrence metabolites
    "pentatriacontane": {"chebi": None, "pubchem": None, "occurrences": 1},
    "coconut  oil": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "oil of cedar wood": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "nutrient broth": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "potato agar": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "4-aminovalerate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "fe(iii) citrate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "flavin adenine dinucleotide": {"chebi": None, "pubchem": None, "occurrences": 1},
    "poly(hexamethylene carbonate)": {"chebi": None, "pubchem": None, "occurrences": 1},
    "poly(tetramethylene carbonate)": {"chebi": None, "pubchem": None, "occurrences": 1},
    "mannoic acid gamma-lactone": {"chebi": None, "pubchem": None, "occurrences": 1},
    "glycerate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "2,3-butanone": {"chebi": None, "pubchem": None, "occurrences": 1},
    "citramalic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "D-ribono-1,4-lactone": {"chebi": None, "pubchem": None, "occurrences": 1},
    "DL-carnitine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "dl-octopamine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "methyl beta-D-glucuronic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "sec-butylamine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "3-hydroxy 2-butanone": {"chebi": None, "pubchem": None, "occurrences": 1},
    "melibionic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "oxalomalic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "indochrome": {"chebi": None, "pubchem": None, "occurrences": 1},
    "L-sorbosone": {"chebi": None, "pubchem": None, "occurrences": 1},

    # Antibiotics - single occurrences
    "verdamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "pyridomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "gardimycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "dynemicin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "fortimicin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "halomicin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "abyssomicin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "abyssomicin C": {"chebi": None, "pubchem": None, "occurrences": 1},
    "abyssomicin D": {"chebi": None, "pubchem": None, "occurrences": 1},
    "abyssomicin G": {"chebi": None, "pubchem": None, "occurrences": 1},
    "abyssomicin H": {"chebi": None, "pubchem": None, "occurrences": 1},
    "atrop-abyssomicin C": {"chebi": None, "pubchem": None, "occurrences": 1},
    "proximicin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "nocardimicin G": {"chebi": None, "pubchem": None, "occurrences": 1},
    "nocardimicin H": {"chebi": None, "pubchem": None, "occurrences": 1},
    "nocardimicin I": {"chebi": None, "pubchem": None, "occurrences": 1},
    "sandramycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "3-trehalosamine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "marinostatin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "chlororaphin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ardacin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ardacin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ardacin C": {"chebi": None, "pubchem": None, "occurrences": 1},
    "dopsisamine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "vancoresmycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "decaplanin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "balhimycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "Ethylenediamine-N,N'-disuccinic acid (EDDS)": {"chebi": None, "pubchem": None, "occurrences": 1},
    "avoparcin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "efrotomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "Cetocycline": {"chebi": None, "pubchem": None, "occurrences": 1},
    "azureomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ristocetin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ristocetin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "nocamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "texazone": {"chebi": None, "pubchem": None, "occurrences": 1},
    "formamicin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cycloviracin B1": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cycloviracin B2": {"chebi": None, "pubchem": None, "occurrences": 1},
    "limocrocin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ascosin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "danomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "achromoviromycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "sarcidin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cystargin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "actinomycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "actinomycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "chlorothricin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ketomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "congocidin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "spiramycin": {"chebi": "CHEBI:85260", "pubchem": "5266", "occurrences": 1},
    "matamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "pamamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "champamycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "rhodomycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "rhodomycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "aureothricin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cellostatin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "amphomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "bluensomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "antimycin A3": {"chebi": None, "pubchem": None, "occurrences": 1},
    "venturicidin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "venturicidin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "flavofungin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "caryomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "angolamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "durhamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "etamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "collinomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "bryamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "griseoviridin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "viridogrisein": {"chebi": None, "pubchem": None, "occurrences": 1},
    "alazopeptin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "griseolutein A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "griseolutein B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "blasticidin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "bandamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cinerubin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "lydimycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "mycobacidin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "glebomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "demecycline": {"chebi": None, "pubchem": None, "occurrences": 1},
    "amicetin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "bamicetin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "plicacetin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "pactamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "staphylomycin M1": {"chebi": None, "pubchem": None, "occurrences": 1},
    "synergistin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "amphotericin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "amphotericin B": {"chebi": "CHEBI:2682", "pubchem": "5280965", "occurrences": 1},
    "cinerubin R": {"chebi": None, "pubchem": None, "occurrences": 1},
    "showdomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "acetomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "fradicin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "naramycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "hortesin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "piericidin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "feldamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "fervenulin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "methylenomycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "beta-Lipomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "spectinomycin": {"chebi": "CHEBI:9215", "pubchem": "15541", "occurrences": 1},
    "streptovaricin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "oxamicetin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "lomofungin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "decoyinine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "psicofuranine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "neoantimycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "stallimycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "netropsin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cladomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "tertiomycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "tertiomycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "enteromycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "tuberactinamine A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "tuberactinomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "azacolutin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "porfiromycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "abikoviromycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "pyrrolomycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "angustmycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "lysocellin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "trans-styrylacetic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "hitachimycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "carminomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "actinotiocin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "kijanimicin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "gelatin hydrolyzed": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex protein hydrolysate
    "nutriacholic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "phoslactomycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "sea salts": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "1,4-propandiol": {"chebi": None, "pubchem": None, "occurrences": 1},
    "2,4-butanediol": {"chebi": None, "pubchem": None, "occurrences": 1},
    "L-xanthine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "1-chlorobutane": {"chebi": None, "pubchem": None, "occurrences": 1},
    "1-chloropropane": {"chebi": None, "pubchem": None, "occurrences": 1},
    "calcium malate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "L-serine": {"chebi": "CHEBI:17115", "pubchem": "5951", "occurrences": 1},
    "tryptone/yeast/beef (tyb)": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "dried grass extract": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "ammonium": {"chebi": "CHEBI:28938", "pubchem": "223", "occurrences": 1},
    "glucose": {"chebi": "CHEBI:4167", "pubchem": "5793", "occurrences": 1},
    "natural seawater (nsw)": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "dnase agar": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex mixture
    "poly-beta-hydroxyalkanoate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "sucrose": {"chebi": "CHEBI:17992", "pubchem": "5988", "occurrences": 1},
    "D-saccharate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "3-[(4-nitrophenyl)carbamoylamino]propanoic acid": {"chebi": None, "pubchem": None, "occurrences": 1},
    "5-bromo-3-indolyl nonanoate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "L-asparagin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "L-arabito": {"chebi": None, "pubchem": None, "occurrences": 1},
    "grisemycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "acetylsalicylate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "o-xylene": {"chebi": None, "pubchem": None, "occurrences": 1},
    "fluostatin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "fluostatin C": {"chebi": None, "pubchem": None, "occurrences": 1},
    "guar gum": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex polysaccharide
    "karaya gum": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex polysaccharide
    "keratin": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex protein
    "transvalencin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "transvalencin Z": {"chebi": None, "pubchem": None, "occurrences": 1},
    "2'-isopentenylsaproxanthin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "4,4-dihydroxy-biphenyl": {"chebi": None, "pubchem": None, "occurrences": 1},
    "potassium hydrogen phthalate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "tallysomycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "tallysomycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "potassium 2-ketogluconate": {"chebi": None, "pubchem": None, "occurrences": 1},
    "miharamycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "miharamycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "plumbemycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "plumbemycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "senfolomycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "senfolomycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cephamycin A": {"chebi": None, "pubchem": None, "occurrences": 1},
    "cephamycin B": {"chebi": None, "pubchem": None, "occurrences": 1},
    "ascamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "dealanylascamycin": {"chebi": None, "pubchem": None, "occurrences": 1},
    "arizonin A1": {"chebi": None, "pubchem": None, "occurrences": 1},
    "arizonin B1": {"chebi": None, "pubchem": None, "occurrences": 1},
    "xanthan gum": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex polysaccharide
    "serum": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex biological fluid
    "butamine": {"chebi": None, "pubchem": None, "occurrences": 1},
    "D-mannose": {"chebi": None, "pubchem": None, "occurrences": 1},
    "blood": {"chebi": None, "pubchem": None, "occurrences": 1},  # Complex biological fluid
}